### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Threnklyn** [fabmade/cert-manager-webhook-ionos#1]
Hi there,

I stumbled upon following error:

```
[{"name":"_acme-challenge.cloud","type":"TXT","content":"4rDTIlJpsOBptsNBe8ZnoRRRTOGP78ythyz6M2iipY0","ttl":120,"prio":0,"disabled":false}]
--
I0419 07:49:17.482897 1 ionos.go:151] Found ID with ZoneName: example.com
E0419 07:49:17.581415 1 client.go:102] Error calling API status: 400 Bad Request url: https://api.hosting.ionos.com/dns/v1/zones/[Zone-ID]/records method: POST
```

This happens if I want to create a wildcard certificate for `*.cloud.example.com`
I manually tried to do the POST call with curl and getting this response:
```
[
  {
    "code": "INVALID_RECORD",
    "message": "Record is invalid.",
    "parameters": {
      "invalidFields": [
        "name"
      ],
      "errorRecord": {
        "name": "_acme-challenge.cloud",
        "rootName": "example.com",
        "type": "TXT",
        "content": "4rDTIlJpsOBptsNBe8ZnoRRRTOGP78ythyz6M2iipY0",
        "ttl": 120,
        "disabled": false
      }
    }
  }
]
```

Maybe Ionos changed their API because changing the name to `_acme-challenge.cloud.example.com` worked for me.
Same 400 Error happens in `ionosClient.GetRecordIdByName()`. The API does not like the query `recordName=_acme.challenge.cloud`

**Comment by fwmarcel** [comment]
hello @Threnklyn 
have you been successful in getting a wildcard certificate u issued in the meantime?
If so what did you do differently?

I am currently not sure in which places I have to enter what.
thanks in advance

**Comment by fabmade** [comment]
@Threnklyn sorry for the late reply, yes i think something is wrong with the ionos api. I have contacted ionos support and I am waiting for a response

**Comment by Threnklyn** [comment]
Fixed it by removing the `recordName` function and replacing its calls with `util.UnFqdn` #2

**Comment by fabmade** [comment]
@Threnklyn ok thank you, for the fix!

**Comment by kaiehrhardt** [comment]
@fabmade
Could you provide a new image tag with the fix?

If you want, i could contribute some github actions automation. (image build + upload)

**Comment by fabmade** [comment]
sure, i created a new tag

**Comment by kaiehrhardt** [comment]
not a git tag... a container image tag https://hub.docker.com/r/fabmade/cert-manager-webhook-ionos/tags

ty

**Comment by derfabianpeter** [comment]
We seem to experience the same issue with a .io domain. cert-manager logs the following error: `"unable to init client `cert-manager`; unable to find ionos dns zone with: io."` while the full domain we try to register a cert for is example.io or sub.example.io. 

We've updated to the [latest](https://hub.docker.com/layers/fabmade/cert-manager-webhook-ionos/latest/images/sha256-bbf35645198b210b0f004bc842fe1eae11c732b0a63d847a137f68d1e85d155c?context=explore) Docker image which I assume should contain the new code that resulted from this issue - but the error seems to persist.
