### ISSUE TITLE
v1beta1.FlowSchema and v1beta1.ProprotyLevelConfiguration are deprecated in k8s v1.28

### ISSUE THREAD

**Issue by deprecastor** [fabmade/cert-manager-webhook-ionos#14]
Hello,

Log from running instance in k8s v1.28
`I0519 23:20:50.356490       1 secure_serving.go:266] Serving securely on :443
I0519 23:20:50.356612       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0519 23:20:50.356644       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0519 23:20:50.356687       1 dynamic_serving_content.go:129] "Starting controller" name="serving-cert::/tls/tls.crt::/tls/tls.key"
I0519 23:20:50.356770       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0519 23:20:50.445924       1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0519 23:20:50.445963       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0519 23:20:50.446007       1 apf_controller.go:299] Starting API Priority and Fairness config controller
I0519 23:20:50.446075       1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0519 23:20:50.446113       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
E0519 23:20:50.449778       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0519 23:20:50.546413       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
I0519 23:20:50.946003       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
I0519 23:20:51.046061       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0519 23:20:51.046145       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
E0519 23:20:51.946349       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
[...]
E0519 23:30:09.989050       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0519 23:30:15.720793       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0519 23:30:56.224947       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0519 23:31:02.047977       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0519 23:31:34.583678       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0519 23:31:44.746445       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
E0519 23:32:20.504951       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0519 23:32:22.355989       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
`

I would guess this is related to Kubernetes dropping the v1beta1.FlowSchema resource in [version 1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26) and will drop even v1beta2 in [version 1.29](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-29).

For a first approach I try enable the old API by some extra args for the Kube-API server with "runtime-config" but this seems not to help.

I guess if the minimal version of Cert-Manager be referenced on, would be 1.12.1 or 1.11.3 the AFP could be turned of. [This ticket](https://github.com/cert-manager/cert-manager/issues/6035) is related to this.

Greetings :-)

**Comment by fabmade** [comment]
thanks, i merged your PR,i think with that changes it will be fixed right? let me know if it is not so.
Best regards
