### ISSUE TITLE
need support

### ISSUE THREAD

**Issue by fwmarcel** [fabmade/cert-manager-webhook-ionos#3]
hello @fabmade 
I do not get on with the installation or configuration.
I have installed the helm chart and the cert manager and added the secret with my values.
I have also created the issuer and certificate. 
However, I fail at this point.
What must be under groupName? The name of the domain?
Thanks for the help

**Comment by fabmade** [comment]
hello @fwmarcel,

no the group name is the defined in the helm chart, therefore you must use the same as there specifed. see https://github.com/fabmade/cert-manager-webhook-ionos/blob/master/deploy/cert-manager-webhook-ionos/values.yaml
you only have to adjust the places marked with <>, for example \<your-email> or \<your-public-key>...

Best regards

**Comment by fwmarcel** [comment]
hello @fabmade 

thank you first of all for the hint. Then I have already done that correctly. 
However, I still fail.
My certificate request is always in the state Ready = False.
Since I am not yet an expert in Kubernetes, I do not know where to start to find a solution.
In the log of the ionos webhook I did not find any hints that point to an error.

With kind regards

**Comment by fwmarcel** [comment]
problem has solved itself.
thanks a lot
