### ISSUE TITLE
provide a helm chart index to be able to install the chart without source download

### ISSUE THREAD

**Issue by kaiehrhardt** [fabmade/cert-manager-webhook-ionos#5]

**Comment by fabmade** [comment]
thank you  @ricsanfre

**Comment by ricsanfre** [comment]
@fabmade, as indicated the PR, a branch named `gh-pages` need to be created and github pages need to be activated pointing to that branch.
Without this branch and the activation of github pages, helm releaser action is not able to create `index.yaml` file and the repo is not available at `https://fabmade.github.io/cert-manager-webhook-ionos`.
