### ISSUE TITLE
Selfhosting helm chart requires activation of githubpages

### ISSUE THREAD

**Issue by ricsanfre** [fabmade/cert-manager-webhook-ionos#8]
As stated in PR #7, branch named `gh-pages` need to be created and github pages need to be activated pointing to that branch.

Without this branch and the activation of github pages, helm releaser action is not able to create index.yaml file and the repo is not available at https://fabmade.github.io/cert-manager-webhook-ionos

**Comment by fabmade** [comment]
@ricsanfre is fixed
