### ISSUE TITLE
Helm repo still does not contain index.yml file

### ISSUE THREAD

**Issue by ricsanfre** [fabmade/cert-manager-webhook-ionos#9]
Helm repo is still not working because index.yaml file is missing in `gh-pages` branch.

## Error debugging

1) Before creating `gh-pages` branch, github action helm chart releaser failed because gh-pages branch was not created.

![image](https://user-images.githubusercontent.com/84853324/192088880-1d81e2fe-c665-40f9-98aa-4e2f3323d6af.png)

See error indicating it could create index.yml file because it did not find `gh-pages` branch. Even with this faulure the tar file containing the chart release was created: https://github.com/fabmade/cert-manager-webhook-ionos/releases/tag/cert-manager-webhook-ionos-1.0.0

2)  After creating `gh-pages`branch, last execution of github action helm chart releaser did not update index.yaml file because the chart (cert-manager-webhook-ionos-1.0.0) was already generated by execution 1)

![image](https://user-images.githubusercontent.com/84853324/192088955-2f9df685-a3de-4101-8ecd-a9adb1336b20.png)

## How to solve this issue:

I guess the way to solve this issue is, either increasing chart version modifying [Chart.yaml file](https://github.com/fabmade/cert-manager-webhook-ionos/tree/master/charts/cert-manager-webhook-ionos/Chart.yaml) to 1.0.1, or deleting current tagged release https://github.com/fabmade/cert-manager-webhook-ionos/releases,  and re-launching chart releaser github action

**Comment by fabmade** [comment]
@ricsanfre index.yaml is in the gh-pages branch now. let me know if it is working for you!

**Comment by ricsanfre** [comment]
@fabmade, now helm repository at `https://fabmade.github.io/cert-manager-webhook-ionos` is working.

Helm chart can be installed executing following commands:

```shell
helm repo add cert-manager-webhook-ionos https://fabmade.github.io/cert-manager-webhook-ionos
helm install cert-manager-webhook-ionos cert-manager-webhook-ionos/cert-manager-webhook-ionos -n certmanager-system
```
